---
- name: Redhat | Import a key from a url
  ansible.builtin.rpm_key:
    state: present
    key: https://packages.wazuh.com/key/GPG-KEY-WAZUH

- name: Redhat | Copy repo informations
  ansible.builtin.copy:
    dest: /etc/yum.repos.d/wazuh.repo
    content: |
      [wazuh_repo]
      gpgcheck=1
      gpgkey=https://packages.wazuh.com/key/GPG-KEY-WAZUH
      enabled=1
      name=Wazuh repository
      baseurl=https://packages.wazuh.com/{{ wazuh_version }}/yum/
      protect=1
    mode: '0644'

- name: Redhat | Install wazuh-agent package
  ansible.builtin.yum:
    name: wazuh-agent
    state: present
  environment:
    WAZUH_MANAGER: "{{ wazuh_manager_ip }}"
    WAZUH_MANAGER_PORT: "{{ wazuh_manager_port }}"
    WAZUH_REGISTRATION_PORT: "{{ wazuh_registration_port }}"
    WAZUH_PROTOCOL: "{{ wazuh_manager_protocol }}"
    WAZUH_REGISTRATION_PASSWORD: "{{ wazuh_registration_password }}"
    WAZUH_AGENT_GROUP: "{{ wazuh_agent_group|join(',') }}"
  when: not ansible_check_mode and wazuh_release_package is not defined

- name: Redhat | Install wazuh-agent with defined package version
  ansible.builtin.yum:
    name: "wazuh-agent-{{ wazuh_release_package }}"
    state: present
  environment:
    WAZUH_MANAGER: "{{ wazuh_manager_ip }}"
    WAZUH_MANAGER_PORT: "{{ wazuh_manager_port }}"
    WAZUH_REGISTRATION_PORT: "{{ wazuh_registration_port }}"
    WAZUH_PROTOCOL: "{{ wazuh_manager_protocol }}"
    WAZUH_REGISTRATION_PASSWORD: "{{ wazuh_registration_password }}"
    WAZUH_AGENT_GROUP: "{{ wazuh_agent_group|join(',') }}"
  when: not ansible_check_mode and wazuh_release_package is defined

- name: Redhat | Disable repo update
  ansible.builtin.copy:
    dest: /etc/yum.repos.d/wazuh.repo
    content: |
      [wazuh_repo]
      gpgcheck=1
      gpgkey=https://packages.wazuh.com/key/GPG-KEY-WAZUH
      enabled=1
      name=Wazuh repository
      baseurl=https://packages.wazuh.com/{{ wazuh_version }}/yum/
      protect=1
    mode: '0644'
  when: not wazuh_autoupdate
